openapi: 3.0.0
info: 
  title: Engine API
  version: 1.0.0
  description: An app to generate messages to follow a conversation
servers:
- url: http://localhost:3000/api/v1
  description: The development API server
paths:
  /assistants:
    $ref: ./assistants.yaml#/collection
  /assistants/{id}/skillsets:
    $ref: ./skillsets.yaml#/collection
  /assistants/{id}/skillsets/{skillsetId}:
    $ref: ./skillsets.yaml#/instance
  /assistants/{id}/skillsets/{skillsetId}/converse:
    $ref: ./skillsets.yaml#/converse