openapi: 3.0.0
info: 
  title: Engine API
  version: 1.0.0
  description: An app to generate messages to follow a conversation
servers:
- url: http://localhost:3000/api/v1
  description: The development API server
paths:
  /assistants:
    $ref: ./assistants.yaml#/collection
  /assistants/{id}:
    $ref: ./assistants.yaml#/instance
  /assistants/{id}/skillsets:
    $ref: ./skillsets.yaml#/collection
  /assistants/{id}/skillsets/{skillset}:
    $ref: ./skillsets.yaml#/instance
  /assistants/{id}/skillsets/{skillset}/entities:
    $ref: ./entities.yaml#/collection
  /assistants/{id}/skillsets/{skillset}/entities/{entityId}:
    $ref: ./entities.yaml#/instance
  /assistants/{id}/skillsets/{skillset}/converse:
    $ref: ./skillsets.yaml#/converse